# Imports

In [1]:
import torch

e:\Uni Stuttgart\课程\Intro to DL\my_env\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


# Tensors
## Tensor creation

Tensors are Pytorch's data structure for representing vectors, matrices and higher dimensional tensors.
Tensors contain homogeneous data of fixed size.

Tensors can be initialized from Python objects, e.g., a list of lists of integers, making up a $n\times m$ dimensional array.
You just call `torch.tensor(data)` where `data` is the Python object.
The data type is automatically inferred, but you can override this behavior by setting the `dtype` argument when calling `torch.tensor`, where `dtype` is one of the PyTorch dtypes as listed at https://pytorch.org/docs/stable/tensors.html#data-types.

### Tensors from functions with random or constant values
PyTorch provides several functions to create tensors with random or constant values:
* `torch.ones(size)`: Creates a tensor filled with ones.
* `torch.zeros(size)`: Creates a tensor filled with zeros.
* `torch.eye(size)`: Creates a 2D tensor with ones on the diagonal and zeros elsewhere (identity matrix).
* `torch.rand(size)`: Creates a tensor with random values uniformly distributed between 0 and 1.
* `torch.randn(size)`: Creates a tensor with random values from a normal distribution with mean 0 and variance 1.
* `torch.full(size, fill_value)`: Creates a tensor filled with the specified value.

### Tensors from other tensors
You can create new tensors from existing tensors. This can be done using various functions:
* `torch.clone(tensor)`: Creates a copy of the tensor.
* `tensor.new_tensor(data)`: Creates a new tensor with the same properties (dtype, device) as the original tensor.
* `tensor.expand(size)`: Expands the tensor to a larger size without copying data.
* `tensor.view(size)`: Returns a new tensor with the same data but different shape.
* `tensor.to(dtype)`: Converts the tensor to a different data type.

Note that `size` is a sequence of integers defining the shape of the output tensor, and `dtype` is of type `torch.dtype`, e.g., `torch.float32`.

## Device allocation

You can also specify the device where the tensor lives, e.g., on CPU (default) or GPU.
For this, you can pass the `device` argument to the tensor creation functions, which takes an object of type `torch.device` ([documentation](https://pytorch.org/docs/stable/tensor_attributes.html#torch-device)).
These can be created by calling `torch.device` with a device type, e.g., `'cpu'` or `'cuda'` (for GPU), and an ordinal specifying the the device id.

## Tensor attributes

Attributes allow inspecting some properties of the tensors, e.g., `shape`, `dtype` and `device`.
They can be valuable when creating neural networks.

## Task: Create tensors

1. Create a tensor `A` $\in \mathbb{R}^{3 \times 3}$ using the `torch.tensor()` function. Initialize it with the following values:
$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
$
1. Create a tensor `B` $\in \mathbb{R}^{3 \times 3}$ using the `torch.ones()` function.
2. Create a tensor `C` with shape (3, 3) using the `torch.zeros()` function.
3. Create a randomly initialized float tensor `D` with the same properties as `C`.
4. Inspect the tensors' shape, datatype and device.

> Hint: PyTorch tensors have a nice `str` representation and can be printed on the console.

In [2]:
A=[[1,2,3],[4,5,6],[7,8,9]]
Tensor_A=torch.tensor(A)
Tensor_B=torch.ones(3,3)
Tensor_C=torch.zeros(3,3)
print(Tensor_A.dtype)

torch.int64


## Tensor operations
### Basic operations

There are several operations that can be applied to tensors, including arithmetic, linear algebra, sampling, matrix manipulation, logical, conversion, moving device and more.
For example, two tensors can be added using `+` or `torch.add`, concatenated using `torch.cat` or moved to a new device using `torch.to`.
Conversion to float is done using `Tensor.float`, e.g., `a.float()`.

Basic operations:
* Add two tensors using `torch.add`.
* Multiply two tensors element-wise using `torch.mul`.
* Divide two tensors  element-wise using `torch.div`.

> Note that most tensor operations from `torch` can directly be called on a tensor: `torch.add(a, b)` is equivalent to `a.add(b)`.

### Task: Basic tensor operations

1. Perform the following operations and print the results:

    a) Add tensor `A` and tensor `B` element-wise.

    b) Multiply tensor `A` and tensor `C` element-wise.

    c) Divide tensor `A` by tensor `B` element-wise.

    d) Divide tensor `B` by tensor `C` element-wise.

In [3]:
print(torch.add(Tensor_A, Tensor_B))
print(torch.mul(Tensor_A, Tensor_C))
print(torch.div(Tensor_A, Tensor_B))
print(torch.div(Tensor_B, Tensor_C))

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[inf, inf, inf],
        [inf, inf, inf],
        [inf, inf, inf]])


### Advanced operations

Advanced tensor operations include matrix multiplication, dot product, reshaping, and comparison operations.

* `torch.matmul(tensor1, tensor2)`: Performs matrix multiplication between two tensors.
* `torch.dot(tensor1, tensor2)`: Computes the dot product of two 1D tensors.
* `torch.squeeze(tensor)`: Removes dimensions of size 1 from the shape of a tensor.
* `torch.eq(tensor1, tensor2)`: Compares two tensors element-wise and returns a tensor of the same shape with boolean values.


### Task: Advanced tensor operations

1. Create a tensor `D` with shape (3, 3) using the `torch.eye()` function.
2. Perform the following operations and print the results:
    1. Multiply tensor `A` and tensor `D` using the `torch.matmul()` function.
    2. Calculate the matrix multiplication of tensor `A` and tensor `D` using the `torch.dot()` function.
3. Create a tensor `E` with shape (2, 1) using the `torch.rand()` function.
4. Print the size of tensor `E` and then squeeze its dimensions using the `torch.squeeze()` function. Print the size of the squeezed tensor.
5. Compare tensor `A` and tensor `B` element-wise using the `torch.eq()` function and print the result.

In [13]:
Tensor_D=torch.eye(3,3,dtype=torch.int64)
Multi_AD=torch.matmul(Tensor_A,Tensor_D)
print(Multi_AD)

result=torch.zeros(3,3,dtype=torch.int64)
for i in range(3):
    for j in range(3):
        result[i,j]=torch.dot(Tensor_A[i],Tensor_D[:,j])
print(result)

Tensor_E=torch.rand(2,1)
print(Tensor_E.size())
print(Tensor_E)
squeezed_tensor=torch.squeeze(Tensor_E)
print(squeezed_tensor.size())
print(squeezed_tensor)

print(torch.eq(Tensor_A,Tensor_B))


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([2, 1])
tensor([[0.0358],
        [0.6508]])
torch.Size([2])
tensor([0.0358, 0.6508])
tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])
